import { nanoid } from "nanoid";
import { IoMail } from "react-icons/io5";
import { FaFlag, FaCamera } from "react-icons/fa";
import { FaLocationDot } from "react-icons/fa6";

export const aboutUs = [
  {
    id: nanoid(),
    icon: <IoMail />,
    title: "responsive",
    text: "I'm always available via phone, text, and email for inquiries.",
  },
  {
    id: nanoid(),
    icon: <FaFlag />,
    title: "syndication",
    text: "I market your property locally, nationally, and internationally",
  },
  {
    id: nanoid(),
    icon: <FaLocationDot />,
    title: "virtual tour",
    text: "Let's make your home stand out with a high quality virtual tour.",
  },
  {
    id: nanoid(),
    icon: <FaCamera />,
    title: "Photography",
    text: "Beautiful, high-end photography is part of our marketing plan.",
  },
];

export const strategies = [
  {
    id: nanoid(),
    title: "local Exposure",
    text: "Through our partnership with Nextdoor—used in over 80% of U.S. and nearly all Bay Area —your home gets targeted local exposure. List with Hansen Partners and your home automatically appears on Nextdoor in your neighborhood.",
  },
  {
    id: nanoid(),
    title: "national Exposure",
    text: "We secure strategic positioning and enhancement on Realtor.com, Trulia, and Zillow, driving more consumers to your home and increasing exposure. We will receive every inquiry about your property directly.",
  },
  {
    id: nanoid(),
    title: "international Exposure",
    text: "We promote on prominent international real estate portals, including: Wall Street Journal, LuxuryPortfolio.com, LuxuryRealEstate.com, LeadingRE.com, UniqueHomes.com, China.apr.com, Caimeiju, Juwai, Country Life UK.",
  },
];

export const communities = [
  {
    id: nanoid(),
    img: "https://images.pexels.com/photos/12579667/pexels-photo-12579667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "livermore",
    subtitle: "From wine & science to shopping & entertainment.",
    text: "Livermore has so much to offer! It is a unique blend of its ranch heritage, its notoriety as a wine-growing region, and its ties to science and technology with Lawrence Livermore National Laboratory and Sandia National Laboratories in the community.Livermore residents enjoy a thriving cultural and entertainment scene. From shopping in the historic downtown to performing arts to a wide range of dining options, there's plenty of attractive community amenities. Summertime provides the added value of live outdoor music nearly every day of the week.Livermore boasts more than 40 world-class wineries, all geographically located within minutes from its flourishing downtown. Outdoor enthusiasts can advantage of community hiking trails, bike paths, parks, and sports fields. Community events wine festivals, weekly farmers' markets, and an annual rodeo.Livermore is home to the Centennial Bulb, the world's longest-lasting lightbulb on display at Fire Station #6. ",
  },
  {
    id: nanoid(),
    img: "https://images.unsplash.com/photo-1499310226026-b9d598980b90?q=80&w=3348&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "pleasanton",
    subtitle: "A small town feeling with big city amenities",
    text: `Located about 25 miles east of Oakland, Pleasanton is an Alameda County suburb with a population of more than 82,000. The U.S. Census Bureau has ranked Pleasanton as the wealthiest middle-sized city in the United States. Pleasanton’s location at the crossroads of Highways 680, 580 and 84 make it convenient to transportation. It also has two BART stations.Pleasanton is home to the company headquarters of Workday, Ellie Mae, Roche Molecular Diagnostics, Blackhawk Network Holdings, and Veeva Systems. Other major employers include Kaiser Permanente, Safeway, Oracle, Nordstrom and Macy's. The Alameda County Fairgrounds are located in Pleasanton, where the county fair is held during the last week of June and the first week of July. Pleasanton Ridge Regional Park is located on the west side of town.Pleasanton was ranked number 4 in USA Today's list of "America's 50 Best Cities to Live In" in 2014, number 63 in Money Magazine's list of "The Best Places to Live" in 2010.`,
  },
  {
    id: nanoid(),
    img: "https://res.cloudinary.com/luxuryp/images/f_auto,q_auto/ynygmqus00yzx7rgmkje/dublin_tmp",
    title: "dublin",
    subtitle: "A vibrant and exciting community",
    text: `Dublin bills itself as “The New American Backyard.” From a modest population of about 14,350 in 1982, Dublin has grown to a city of over 63,000 residents. One of the fastest-growing cities in Alameda County, Dublin is projected to have a total population of 75,000 at its fully developed peak.A very forward-thinking town, Dublin offers many different types of housing. Special projects include affordable housing apartments designed in particular for military members and veterans. Townhomes have been build close to transit and shopping. Downtown Dublin even has free wi-fi.City leaders have focused on diversity. The city's location at the crossroads of Highways 580 and 680 and its two BART stations have attracted many large corporations, particularly high tech.There are lots and lots of shops and restaurants here and the many offered cuisines make dining an internationally-flavored experience. `,
  },
];

export const testimonials = [
  {
    id: nanoid(),
    img: "https://i.pravatar.cc/150?img=52",
    author: "rick c.",
    text: "Julie and Brett were extremely informative from start to finish. Excellent communication all the way through the entire process. Julie definitely knows the market. I would use Julie's team for all of my real estate dealings. Excellent all the way",
  },
  {
    id: nanoid(),
    img: "https://i.pravatar.cc/150?img=32",
    author: "erin d.",
    text: "My overall experience with you Julie and your team was very special to me. Making the move back up to the Bay Area after 30 years was not an easy task! I so appreciate your professionalism and expertise during this crazy process.",
  },
  {
    id: nanoid(),
    img: "https://i.pravatar.cc/150?img=31",
    author: "lisa s.",
    text: `I don't know how I would have sold my house if it wasn't for the help from Julie & Brett. THey went above and beyond in many ways. Some of them were: scheduling contractors, staging the house, helping sell the existing furniture in my home. The list could go on and on. All I can say is that the Hansen team is "AMAZING"!"`,
  },
  {
    id: nanoid(),
    img: "https://i.pravatar.cc/150?img=13",
    author: "jim g.",
    text: `Julie has been selling homes in our area for many years we know and trust her we have come back to her many times over the last 30 years she has always done a wonderful job for us. This home will be the 6th home Julie has listed and sold for us!`,
  },
];

export const listings = [
  // Livermore
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41093645/0/0/0/7faa8c3bc7423560b3474ab82a48646f/153/198ca53dab6cf835d111f0aca07f4e6b/41093645-1be9bd4b-e112-4b99-966e-c1460fe0f8c9.JPG",
    area: "livermore",
    price: 1849000,
    address: "2878 4Th St # 1401 Livermore CA, 94550",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41093498/0/0/0/af531d3bb0fb5f74e8859555f2ab18f2/153/fb3e467b472a0c05b649d7bf8db9ed9f/41093498-651765dc-2d4b-4a1f-8eb6-6fa173c2d5b2.JPG",
    area: "livermore",
    price: 1849000,
    address: "2787 Impruneta Ct Livermore CA, 94550",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41091995/0/0/0/b6a2fdd167edf54df8863b80a0d47d7a/153/476d8613d810bf1db9af9001b8895903/41091995-a99253dc-e887-4b48-8029-6d559a47a92d.JPG",
    area: "livermore",
    price: 1849000,
    address: "1208 Riesling Cir Livermore CA, 94550",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41092084/0/0/0/25ca2bdd351e7ee49a5c698eb93dc0a7/152/59dbff7c7f60786db5b600d4d2f5d171/41092084-6d5bddfe-9c6f-456c-932c-7d9d3b13b7b1.JPG",
    area: "livermore",
    price: 1849000,
    address: "238 Prato Way Livermore CA, 94550",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  // Pleasanton
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41093791/0/0/0/09219c03fb64c508f4f63894f111c6c5/153/10ca81131405a0fbce658acf4249e18c/41093791-a4c8fdb2-78be-4715-b0ae-12ce515b5b4d.JPG",
    area: "pleasanton",
    price: 2495888,
    address: "3095 Crestablanca Drive Pleasanton CA, 94566",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41093790/0/0/0/5dba35927af976bd2166eb4d3ef911e3/153/74c0c2d0fe2faeafde9a7e5d94392b3d/41093790-58847fe1-eb2f-4ecf-8029-b0cf982137c5.JPG",
    area: "pleasanton",
    price: 1849000,
    address: "6369 Paseo Santa Maria Pleasanton CA, 94566",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41093748/0/0/0/32d615964b2d23944f7fc28f5816feb6/152/e7f6cb561b408c1d0a3e59fc5ace2dd8/41093748-4d1db962-9bae-4eaf-a0c0-3784025daa77.JPG",
    area: "pleasanton",
    price: 1849000,
    address: "4420 First Pleasanton CA, 94566",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41093552/0/0/0/0721c3a21d725943445cf63e00c83f9d/153/105f2b278731b41b389ab4591b4a36a7/41093552-74bb8d32-abc5-487a-9282-41b614798bbb.JPG",
    area: "pleasanton",
    price: 1849000,
    address: "2839 Victoria Ridge Ct Pleasanton CA, 94566",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  // Dublin
  {
    id: nanoid(),
    img: "https://media.mlslmedia.com/property/MLSL/82002844/833425cc7df74805ac44ace4912e658b/2/1",
    area: "dublin",
    price: 1849000,
    address: "4790 Central Parkway Dublin CA, 94568",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41093525/0/0/0/5e492c675bb0b545ea14cb8aa388d79a/153/78154c0f55aa302f6a0b666c030a82c6/41093525-5C67B70B-1274-428B-B5E0-F08FC4145598.JPG",
    area: "dublin",
    price: 1849000,
    address: "7015 Coombsville Loop Dublin CA, 94568",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41093628/0/0/0/e405e0b5c014dc76a8eee95cdf8eaae5/153/c347f55d0ba0935ad8983d04f0d3565e/41093628-4b7d348a-5c22-4357-afdb-be72d5c3ccc1.JPG",
    area: "dublin",
    price: 1849000,
    address: "5783 Shadow Hill Dr Dublin CA, 94568",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
  {
    id: nanoid(),
    img: "https://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41093523/0/0/0/2259eb4725774ef8dcafd83fb2a01a5c/148/fef4b741c060ca9af8881b99ee794b0d/41093523-84a67d53-032b-4058-a5ad-9803de964364.JPG",
    area: "dublin",
    price: 1849000,
    address: "3275 Dublin Blvd Unit: 217 Dublin CA, 94568",
    perSqft: 740.84,
    type: "residential",
    garages: 3,
    builtIn: 1991,
    interior: [
      "Bonus/Plus Room",
      "Kitchen/Family Combo",
      "Office, Rec/Rumpus Room",
      "Storage",
      "Counter - Solid Surface",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Pantry",
      "Updated Kitchen",
      "Central Vacuum",
    ],
    exterior: [
      "Backyard",
      "Back Yard",
      " Front Yard",
      "Sprinklers Automatic",
      "Sprinklers Back",
      "Sprinklers Front",
      "Terraced Up",
      "Landscape Back",
      "' Landscape Front'",
      "Yard Space",
    ],
    parking: [
      "Attached",
      "Int Access From Garage",
      "Garage Faces Front",
      "Garage Door Opener",
    ],
    mls: 41093791,
  },
];
